services:
  # Dedicated controller-only node (no broker role)
  controller-0:
    image: apache/kafka:latest
    container_name: controller-0
    environment:
      KAFKA_NODE_ID: 1  # Unique node ID for this Kafka node
      KAFKA_PROCESS_ROLES: controller  # This node acts only as a controller
      KAFKA_LISTENERS: CONTROLLER://:9091  # Controller traffic: listens on port 9091
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER  # Listener name for controller communication
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT  # Security protocol mapping
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-0:9091, 2@broker-controller-0:9091, 3@broker-controller-1:9091  # Quorum voters
      CLUSTER_ID: kraft-cluster  # Cluster ID for the KRaft cluster
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs  # Log directory for Kafka metadata
    networks:
      - kafka-net

  # Broker + Controller combo node
  broker-controller-0:
    image: apache/kafka:latest
    container_name: broker-controller-0
    ports:
      - 19092:9092  # External access to broker on port 19092
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller  # This node acts as both broker and controller
      KAFKA_LISTENERS: INTERNAL://:9090, CONTROLLER://:9091, EXTERNAL://:9092  # Listener setup
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-controller-0:9090, EXTERNAL://localhost:19092  # Advertised listeners
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL  # Listener used for inter-broker communication
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-0:9091, 2@broker-controller-0:9091, 3@broker-controller-1:9091
      CLUSTER_ID: kraft-cluster
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    networks:
      - kafka-net

  # Another Broker + Controller combo node
  broker-controller-1:
    image: apache/kafka:latest
    container_name: broker-controller-1
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_LISTENERS: INTERNAL://:9090, CONTROLLER://:9091, EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-controller-1:9090, EXTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-0:9091, 2@broker-controller-0:9091, 3@broker-controller-1:9091
      CLUSTER_ID: kraft-cluster
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    networks:
      - kafka-net

  # Broker-only node
  broker-0:
    image: apache/kafka:latest
    container_name: broker-0
    ports:
      - 39092:9092  
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker  # This node acts only as a broker
      KAFKA_LISTENERS: INTERNAL://:9090, EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-0:9090, EXTERNAL://localhost:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-0:9091, 2@broker-controller-0:9091, 3@broker-controller-1:9091
      CLUSTER_ID: kraft-cluster
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    networks:
      - kafka-net

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      - controller-0
      - broker-controller-0
      - broker-controller-1
      - broker-0

    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker-0:9090

    networks:
      - kafka-net

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: broker-controller-0:9090,broker-controller-1:9090,broker-0:9090
      SCHEMA_REGISTRY: http://schema-registry:8081
    depends_on:
      - broker-controller-0
      - broker-controller-1
      - broker-0
      - schema-registry

    networks:
      - kafka-net

# Kafka custom network for internal communication
networks:
  kafka-net:
    driver: bridge  